### ISSUE TITLE
PFP not in FP course list on slide #14

### ISSUE THREAD

**Issue by valderman** [emilaxelsson/fp-presentation-15#2]
It seems a bit weird to have programming paradigms, which isn't even running this year, in the list of FP courses (slide #14) when PFP is not, doesn't it? Also, shouldn't AFP be on that slide?

**Comment by patrikja** [comment]
If you refer to this file:
https://github.com/emilaxelsson/fp-presentation-15/blob/master/slides/slides.hs
and the slide 
kurserFP1 :: Slide
then it clearly lists both FP, AFP and PFP so I don't see the problem?

**Comment by valderman** [comment]
The list of courses cut off so neatly at the bottom of my screen that I figured the list just ended there, when in reality it was just my screen that was too small to fit them all. Oops!
